### DISCUSSION TITLE
¿Como elimino el campo de envios en el carrito?

### DISCUSSION THREAD

**Discussion by valentinavidarte** [woocommerce/woocommerce#51122] [Checkout Flow]
El campo de envío aparece en el carrito y luego en la de finalizar compra aparece retiro o envío nuevamente. Me gustaria que solo quede en el de finalizar compra. No se como borrarlo,pero no me gusta. 
![Captura](https://github.com/user-attachments/assets/e7a7f727-ce46-49d0-b970-9d41f38039c7)

**Comment by mikejolley** [comment]
We only support hiding the shipping calculator form, not the rates themselves. cc @senadir

**Comment by senadir** [comment]
Removing it is not supported for now. You can hide it with CSS:

```css
.wp-block-woocommerce-cart-order-summary-shipping-block {
    display: none;
}
```
