### DISCUSSION TITLE
Configurable display fields

### DISCUSSION THREAD

**Discussion by xorinzor** [woocommerce/woocommerce#51719] [Checkout Flow]
In the "Cart Line Items" element it would be nice if the products shown are configurable, specifically which fields from the product are shown.

For example, I'd like to see the "size" attribute of a product, but don't need the short description to be shown.

**Comment by mikejolley** [comment]
Hello

I think this is a similar request to https://github.com/woocommerce/woocommerce/issues/42602.

While its not currently possible to customise this in the editor, you can remove that part using some custom CSS e.g.

```css
.wc-block-cart .wc-block-components-product-metadata__description { display: none} 
```

Since this is covered by #42602 Ill close this topic but hope that helps.
