### DISCUSSION TITLE
Possibility to enable only local Pickup

### DISCUSSION THREAD

**Discussion by 262media** [woocommerce/woocommerce#52460] [Checkout Flow]
I need to setup a shop that has only local pickup and COD. I should be able to get rid of the shipping tab on the checkout.

**Comment by nielslange** [comment]
Hello @262media 👋

Thank you for reaching out! This feature was also requested in issues #48509 and #50409. While I don’t have an estimated timeline for when we’ll be able to address it, please know that it’s on our radar, and we’ll be tracking progress in #48509.

Meanwhile, you can temporarily hide the `Delivery` section by adding the following custom CSS to your site:

```css
/* Hide the delivery section on the Checkout block when only Local Pickup is available */
.wp-block-woocommerce-checkout-shipping-method-block {
	display: none;
}
```

Please note that the custom CSS code should be treated as a temporary solution until the issue #48509 has been addressed.
