### DISCUSSION TITLE
Limiting image size on Single Product

### DISCUSSION THREAD

**Discussion by goclimbing** [woocommerce/woocommerce#53387] [General]
On large monitors the image on the single product page is way to large.  I've searched and tried many things to limit their size but nothing is netting a positive result. I was able to remove the magnification and link to the image which is also a requirement.

setting the size in the Customizer only reduces the actual image size (it'll make it 300 px wide if I set that but then it gets blown up on display and looks grainy).

https://store.lafarge.net/product/test-product/

Hoping to do this via CSS and not muck with templates.

Theme is Understrap but that doesn't seem to matter.  Full width flexible content main template.

Thanks in advance.

**Comment by nielslange** [comment]
Hello @goclimbing 👋

To adjust the size of a single product image using CSS, you could use the following CSS code:

```css
.woocommerce-product-gallery__image {
    display: flex;
    justify-content: flex-end;
  }
  
  .woocommerce div.product div.images img {
    max-width: 100px;
  }
```

That said, I see that your product page is full width. This leads to the big product image. Instead of adjusting the size of the product image, I'd rather adjust the width of the product page itself. A smaller page width, e.g. by centring the content, increases the usability of the site and increases the readability of the texts.
