### ISSUE TITLE
Single Product Page Tab Style Issue

### ISSUE THREAD

**Issue by obiPlabon** [woocommerce/woocommerce#18476]
WooCommerce tab style doesn't look smooth with default style. I've tasted using **TwentyFifteen** theme. Here is the visual comparison:

### Before
![wc-product-tabs-before](https://user-images.githubusercontent.com/10244644/34914680-a0a6db18-f941-11e7-97e9-a619726ba4f5.png)

### After
![wc-product-tabs-after](https://user-images.githubusercontent.com/10244644/34914679-5545bae0-f941-11e7-8ec0-b8b4cc871361.png)

I changed the position value of the following selectors to make the rounded edge smooth.
``` CSS
.woocommerce div.product .woocommerce-tabs ul.tabs li::before {
    left: -5px;
}
.woocommerce div.product .woocommerce-tabs ul.tabs li::after {
    right: -5px;
}
``` 

Thanks
