### ISSUE TITLE
PhotoSwipe styles with !important in woocommerce.css

### ISSUE THREAD

**Issue by markfinst** [woocommerce/woocommerce#19663]
There are styles in [woocommerce.css](https://github.com/woocommerce/woocommerce/blob/6e13ac7dc2e2feafc9e9a5f68802d47a2422fe00/assets/css/woocommerce.scss#L1636) that use both `!important` and selectors with high specifity - `tag.class`. Sometimes, developers want to use their own "skin" fpr PhotoSwipe and these styles are very hard to override without writing ugly CSS.

```css
/**
 * Photoswipe
 * 1. These styles are required to overwrite default theme button styles (Twenty Twelve adds gradients via background-image).
 * 2. For zooming on mobile.
 */
.pswp {
	z-index: 999999;
}

.woocommerce img.pswp__img,
.woocommerce-page img.pswp__img {
	max-width: none; /* 2 */
}

button.pswp__button {
	box-shadow: none !important;
	background-image: url('photoswipe/default-skin/default-skin.png') !important;
}

button.pswp__button,
button.pswp__button:hover,
button.pswp__button--arrow--left::before,
button.pswp__button--arrow--right::before {
	background-color: transparent !important; /* 1 */
}

button.pswp__button--arrow--left,
button.pswp__button--arrow--right,
button.pswp__button--arrow--left:hover,
button.pswp__button--arrow--right:hover {
	background-image: none !important; /* 1 */
}
```

WooCommerce has amazing feature to remove lightbox: 

```php
remove_theme_support( 'wc-product-gallery-lightbox' );
``` 

it excludes photoswipe css/js files and allows to use own JS file and own skin (CSS file). The problem is that `woocommerce.css` is unchanged.

## Proposal 1

Move these styles to PhotoSwipe css file, so it's possible to exclude them when excluding PhotoSwipe via `remove_theme_support`

## Proposal 2

Add class to root element of PhotoSwipe (HTML is located [in photoswipe.php](https://github.com/woocommerce/woocommerce/blob/2d85b5adde9b074e077100cb67eec7d3027a45d0/templates/single-product/photoswipe.php)) and scope styles.

`woocommerce.css`:

```css
.woocommerce-pswp button.pswp__button {
	box-shadow: none !important;
	background-image: url('photoswipe/default-skin/default-skin.png') !important;
}
```

and `photoswipe.php`:

```html
<div class="pswp woocommerce-pswp" tabindex="-1" role="dialog" aria-hidden="true">
```
