### ISSUE TITLE
Review link: add a way to remove the parentheses

### ISSUE THREAD

**Issue by dashkevych** [woocommerce/woocommerce#25735]
By default, the review text is shown in parentheses. Since these parentheses are added to the text, it makes it hard to remove them.

![Woo review link HTML](https://snipboard.io/1O4UQ3.jpg)

**Describe the solution you'd like**
It would be great if we have an option to remove these parentheses.

**Describe alternatives you've considered**
We can use a CSS to display these parentheses. For example:

```css
.woocommerce-review-link::before {
  content: "("
}

.woocommerce-review-link::after {
  content: ")";
}
```

In this case, it will be easier to remove them using a custom CSS.
