### ISSUE TITLE
Use the root CSS color variables in all stylesheets?

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce#29574]
We noticed recently a set of root variables has been added which includes colors: https://github.com/woocommerce/woocommerce/issues/28707

Can Woo's stylesheets use these rather than hardcoding colors like this:
https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/assets/css/woocommerce.scss#L85

This would mean a theme developer can then override the root variables to effect the colors across the website rather than needing to override every single element where the colors are hardcoded. This is particular useful if you need to update (for example) the red color WooCommerce uses throughout the website (remove from cart buttons, error notices, etc) to be a website's red hex color from brand guidelines.

We added a similar request previously at: https://github.com/woocommerce/woocommerce/issues/28546 - I'm not sure now we have these root variables if it's best to also include a filter/settings for this or just leave as CSS overrides.

What do you think?

**Comment by helgatheviking** [comment]
+1 for reworking the SCSS files to use CSS variables where possible. With the heavily nested nature of the SCSS stylesheets, it can be a real pain to override Woo's style rules.

**Comment by helgatheviking** [comment]
@ninetyninew would you give my PR a test run?

**Comment by ninetyninew** [comment]
@helgatheviking I'm just having a few days off for Easter but will try to check this out when back. From a brief look that does look like it would fine for what I'm talking about here. The only thing I can think of is if Woo still supports IE11 (?) we maybe still need the existing values as a fallback?

**Comment by juliaamosova** [comment]
Thanks for submitting your suggestions and PR @helgatheviking!

**Comment by ethanclevenger91** [comment]
Just an additional thought here - I'm assuming there's some set of guidelines that approved/recommended Woo add-ons are supposed to adhere to. Adding these CSS variable to those guidelines and ensuring all add-ons use it would also be a huge help.

For example, right now, there is no centralized site-wide notice system, even among the core Woo add-ons, so the store notice in core and the missing profile fields notice in the Memberships add-on, for instance, use different site-wide notice bars and implement these styles (like the purple background) completely independent of each other.

**Comment by erikyo** [comment]
@ninetyninew @ethanclevenger91, would you provide a feedback on that way to set the custom props? would this meet your needs? You could give a try editing the css custom props on my blog [here](https://modul-r.codekraft.it/product/logo-collection/) should change dynamically as soon as you insert new values, for example changing --wc--primary-hue: 180 
![image](https://user-images.githubusercontent.com/8550908/152864507-9455f172-ef14-4815-8969-ca98e346c6f5.png)

**Comment by JacobDB** [comment]
Has there been any movement on this at all? I want to write a simple stylesheet that makes WooCommerce fit the designs of the websites we develop, but with the way this is now, I constantly have to update the stylesheet to reflect changed selectors with updates (the recent "`:where()`" change basically broke everything...). If I could simply set the color scheme (and ideally font family) using CSS custom properties, that'd save me a lot of headache when it comes to maintenance.

I just want to use the core WooCommerce styles, with some minor color tweaks, and it's kind of crazy that this is so difficult. Maybe a separate stylesheet could be added that gets used when you turn on a particular setting (i.e. "Use CSS Custom Properties")?

**Comment by alapiere** [comment]
It's getting worse and worse.. latest woocommerce update 9.6.1 adding ugly purple on all MY websites. 
they're not Woocommerce demo , they're production website for clients ! don't mess with them, devs , play with your own demo theme ! 

or at the very least, make it simple to override
what is the use of having
```css
@charset "UTF-8";:root {
    --woocommerce: #720eec;
    --wc-green: #7ad03a;
    --wc-red: #a00;
    --wc-orange: #ffba00;
    --wc-blue: #2ea2cc;
    --wc-primary: #720eec;
    --wc-primary-text: #fcfbfe;
    --wc-secondary: #e1d0f6;
    --wc-secondary-text: #47276d;
    --wc-highlight: #958e09;
    --wc-highligh-text: white;
    --wc-content-bg: #fff;
    --wc-subtext: #767676
}
```

if every bit of purple is hardcoded in the css ????
```css
#add_payment_method #payment div.payment_box, .woocommerce-cart #payment div.payment_box, .woocommerce-checkout #payment div.payment_box {
    background-color: #d4bbf2;
    color: #47276d;
}
```
or put your branding things in your own dequeuable style, 
```php
add_filter( 'woocommerce_enqueue_styles',function(){
        //unset( $enqueue_styles['woocommerce-ugly-purple-theme'] );      // Put all the woocommerce branding here
});
```

and you can't suggest to 
unset( $enqueue_styles['woocommerce-general'] );
and keep
$enqueue_styles['woocommerce-layout'] );
it breaks all the layout so the distinction is obviously not respected
